services:
  db:
    image: postgres:16-alpine
    container_name: kmutnb_postgres
    restart: always
    environment:
      POSTGRES_DB: kmutnb_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "-c listen_addresses='*'"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: kmutnb_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin.tm@sci.kmutnb.ac.th
      PGADMIN_DEFAULT_PASSWORD: admintm
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
